name: "Test Pull Request"

concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  test-pkgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        shell: bash
        
      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - name: Install dependencies
        shell: bash
        run: yarn install --immutable

      - name: Check release definition
        # Don't run on changeset-release branch as it does not require a changeset to update
        # package versions. Simplifies the automation of package versioning and allows
        # branch protection rules
        if: github.head_ref != 'changeset-release/main'
        run: yarn release:status
     
      # Fails if project references drift from package.json, fix with reference script
      - name: Check project reference
        run: yarn reference:check

      - name: Test packages
        run: yarn workspaces foreach --topological --parallel run test

      - name: Lint packages
        run: yarn workspaces foreach --topological --parallel run lint

      - name: Post coverage
        uses: ScaCap/code-coverage-assistant@v1 
        # only post on PRs
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          monorepo-base-path: "./packages" 
